@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package personal.vanmuur.glyphmod;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;